import pytest

from src.text_justification import Solution


@pytest.mark.parametrize(
    "expected,words,max_width",
    (
        (
            ["This    is    an", "example  of text", "justification.  "],
            ["This", "is", "an", "example", "of", "text", "justification."],
            16,
        ),
        (
            ["What   must   be", "acknowledgment  ", "shall be        "],
            ["What", "must", "be", "acknowledgment", "shall", "be"],
            16,
        ),
        (
            [
                "Science  is  what we",
                "understand      well",
                "enough to explain to",
                "a  computer.  Art is",
                "everything  else  we",
                "do                  ",
            ],
            [
                "Science",
                "is",
                "what",
                "we",
                "understand",
                "well",
                "enough",
                "to",
                "explain",
                "to",
                "a",
                "computer.",
                "Art",
                "is",
                "everything",
                "else",
                "we",
                "do",
            ],
            20,
        ),
        (
            [
                "The     important",
                "thing  is  not to",
                "stop questioning.",
                "Curiosity has its",
                "own   reason  for",
                "existing.        ",
            ],
            [
                "The",
                "important",
                "thing",
                "is",
                "not",
                "to",
                "stop",
                "questioning.",
                "Curiosity",
                "has",
                "its",
                "own",
                "reason",
                "for",
                "existing.",
            ],
            17,
        ),
        (
            [
                "Give  me  my  Romeo; and,",
                "when  he  shall die, Take",
                "him  and  cut  him out in",
                "little stars, And he will",
                "make  the  face of heaven",
                "so   fine  That  all  the",
                "world  will  be  in  love",
                "with  night  And  pay  no",
                "worship   to  the  garish",
                "sun.                     ",
            ],
            [
                "Give",
                "me",
                "my",
                "Romeo;",
                "and,",
                "when",
                "he",
                "shall",
                "die,",
                "Take",
                "him",
                "and",
                "cut",
                "him",
                "out",
                "in",
                "little",
                "stars,",
                "And",
                "he",
                "will",
                "make",
                "the",
                "face",
                "of",
                "heaven",
                "so",
                "fine",
                "That",
                "all",
                "the",
                "world",
                "will",
                "be",
                "in",
                "love",
                "with",
                "night",
                "And",
                "pay",
                "no",
                "worship",
                "to",
                "the",
                "garish",
                "sun.",
            ],
            25,
        ),
    ),
)
def test_solution(expected, words, max_width):
    assert expected == Solution().fullJustify(words, max_width)
